---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/{{ deploy_user }}/reddit
        version: monolith
      notify: restart puma

    - name: Bundler install
      bundler:
        state: present
        chdir: /home/{{ deploy_user }}/reddit
      notify: restart puma

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: restart reddit.service
      service:
        name: reddit.service
        state: restarted

    - name: restart puma
      systemd: name=puma state=restarted
