---
- name: Install Mongo
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: Install mongodb
    apt:
      name: mongodb
      state: present

  - name: Enable mongodb service
    service:
      name: mongodb
      enabled: true
