---
- name: Deploy App
  hosts: app
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart reddit.service

    - name: Bundler install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes

  handlers:
    - name: restart reddit.service
      become: true
      service:
        name: reddit.service
        state: restarted
